# Generated by Django 3.2.15 on 2022-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_squashed_0012_userchannel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
