# Generated by Django 3.0.3 on 2020-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessagemodel_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='read_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
