# Generated by Django 3.0.3 on 2020-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='room',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
