# Generated by Django 3.0.3 on 2020-04-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_userchannel_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchannel',
            options={'ordering': ('-created',), 'verbose_name': 'Canale Utente', 'verbose_name_plural': 'Canali Utenti'},
        ),
    ]
