# Generated by Django 3.0.6 on 2020-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200402_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
