# Generated by Django 2.0.3 on 2018-08-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Utenti PEO UNICAL'},
        ),
    ]
