# Generated by Django 2.2.4 on 2019-08-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0004_user_email_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='Operatore interno'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_utente',
            field=models.BooleanField(default=False, verbose_name='Utente organizzazione'),
        ),
    ]
