# Generated by Django 2.2.4 on 2019-08-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0005_auto_20190805_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
    ]
