# Generated by Django 3.0.4 on 2020-03-11 16:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0007_remove_user_is_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codice_fiscale',
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TaxPayer ID - codice fiscale'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=django_countries.fields.CountryField(blank=True, max_length=30, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
