site_name: uniTicket - docs (v2.9.2)
site_author: Università della Calabria

theme:
  name: material
  logo: assets/logo_unical_white.svg
  # palette:
  #   scheme: default # o 'slate' per il tema scuro
  #   primary: indigo
  #   accent: indigo
  # scheme: state   # "default" per tema chiaro, "slate" per tema scuro
  features:
    - navigation.path    # breadcrumbs
    # - navigation.tabs    # Menu orizzontale in alto
    - search.suggest     # Suggerimenti durante la ricerca
    - content.code.copy  # Bottone per copiare il codice
    # - content.code.annotate  # Abilita le annotazioni (1) (2)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details  # Opzionale: per alert collassabili

extra:
  version: 2.9.2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UniversitaDellaCalabria

extra_css:
  - assets/stylesheets/extra.css

copyright: |
  Università della Calabria (www.unical.it)

nav:
  - Cos'è?: index.md
  - Caratteristiche: caratteristiche.md
  - Componenti: componenti.md
  - Setup:
    - Installazione: setup/installazione.md
    - Database: setup/database.md
    - Configurazione: 
        - File settingslocal.py: setup/configurazione/settingslocal.md
        - Parametri obbligatori: setup/configurazione/parametri-obbligatori.md
        - Personalizzazione: setup/configurazione/personalizzazione.md
        - Parametri avanzati: setup/configurazione/parametri-avanzati.md
        - Bootstrap Italia: setup/configurazione/bootstrap_italia.md
        - Autenticazione SAML2: setup/configurazione/sso_saml2.md
    - Run: setup/run.md
    - Docker: setup/docker.md
    - Migrazione da v1 a v2: setup/migrazione/v1-v2.md
  - Aree organizzative:
    - Strutture: aree-organizzative/strutture.md
    - Uffici: aree-organizzative/uffici.md
  - Richieste (Ticket): ticket/index.md
  - Attività (Task): task/index.md
  - Tipologie di richieste: tipologie/index.md
  - Ruoli degli utenti:
    - Utente semplice:
      - Panoramica: ruoli/utente/index.md
      - Dashboard: ruoli/utente/dashboard.md
      - Nuova richiesta: ruoli/utente/nuovo-ticket.md
      - Messaggi: ruoli/utente/messaggi.md
      - Account: ruoli/utente/account.md
    - Operatore:
      - Panoramica: ruoli/operatore/index.md
      - Dashboard: ruoli/operatore/dashboard.md
      - Gestione delle richieste: ruoli/operatore/gestione.md
    - Manager:
      - Panoramica: ruoli/manager/index.md
      - Dashboard: ruoli/manager/dashboard.md
      - Gestione delle tipologie: ruoli/manager/gestione-tipologie.md
      - Gestione degli uffici: ruoli/manager/gestione-uffici.md
      - Statistiche: ruoli/manager/statistiche.md