# Generated by Django 3.1.6 on 2022-03-27 17:52

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import organizational_area.models


class Migration(migrations.Migration):

    replaces = [('organizational_area', '0001_initial'), ('organizational_area', '0002_auto_20190305_1020'), ('organizational_area', '0003_auto_20190305_1048'), ('organizational_area', '0004_organizationalstructurefunction_structure'), ('organizational_area', '0005_remove_organizationalstructurefunction_structure'), ('organizational_area', '0006_auto_20190305_1129'), ('organizational_area', '0007_auto_20190305_1445'), ('organizational_area', '0008_auto_20190305_1527'), ('organizational_area', '0009_auto_20190305_1843'), ('organizational_area', '0010_auto_20190312_1021'), ('organizational_area', '0011_auto_20190312_1034'), ('organizational_area', '0012_auto_20190312_1035'), ('organizational_area', '0013_auto_20190312_1054'), ('organizational_area', '0014_remove_organizationalstructureoffice_is_default'), ('organizational_area', '0015_organizationalstructureoffice_is_default'), ('organizational_area', '0016_remove_organizationalstructure_seat'), ('organizational_area', '0017_organizationalstructure_slug'), ('organizational_area', '0018_organizationalstructureoffice_slug'), ('organizational_area', '0019_auto_20190411_1001'), ('organizational_area', '0020_auto_20190415_0945'), ('organizational_area', '0021_auto_20190503_1546'), ('organizational_area', '0022_auto_20200313_1406'), ('organizational_area', '0023_organizationalstructure_banner'), ('organizational_area', '0024_auto_20200330_1232'), ('organizational_area', '0025_auto_20200406_1150'), ('organizational_area', '0026_usermanagestructure'), ('organizational_area', '0027_auto_20200504_2312'), ('organizational_area', '0028_auto_20200505_1149'), ('organizational_area', '0029_auto_20200624_0913'), ('organizational_area', '0030_auto_20200624_0944'), ('organizational_area', '0031_auto_20200702_1126'), ('organizational_area', '0032_organizationalstructureoffice_is_private')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipments Type',
                'verbose_name': 'Equipment Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('unique_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=768, null=True)),
                ('seat', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structures',
                'verbose_name': 'Organizational Structure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure functions',
                'verbose_name': 'Organizational Structure function',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.EquipmentType')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.OrganizationalStructureFunction')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure locations',
                'verbose_name': 'Organizational Structure location',
                'ordering': ['organizational_structure'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
                ('is_default', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure Offices',
                'verbose_name': 'Organizational Structure Office',
                'ordering': ['name'],
                'unique_together': {('slug', 'organizational_structure')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.EquipmentType')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.OrganizationalStructureFunction')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructureoffice')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure office locations',
                'verbose_name': 'Organizational Structure office location',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure types',
                'verbose_name': 'Organizational Structure type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='structure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational_area.organizationalstructuretype'),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructureoffice')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure Office Employees',
                'verbose_name': 'Organizational Structure Office Employee',
                'ordering': ['-create_date'],
                'unique_together': {('employee', 'office')},
            },
        ),
        migrations.RemoveField(
            model_name='organizationalstructure',
            name='seat',
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Lo slug deve contenere almeno un carattere alfabetico', regex='^(?=.*[a-zA-Z])')]),
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=organizational_area.models._logo_upload),
        ),
        migrations.CreateModel(
            name='UserManageOrganizationalStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'organizational_structure')},
            },
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
