# Generated by Django 3.2.12 on 2022-03-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0001_squashed_0032_organizationalstructureoffice_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructureofficeemployee',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructureoffice'),
        ),
    ]
