# Generated by Django 2.1.7 on 2019-03-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0004_organizationalstructurefunction_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalstructurefunction',
            name='structure',
        ),
    ]
