# Generated by Django 2.1.7 on 2019-03-05 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0005_remove_organizationalstructurefunction_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructureofficeemployee',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
