# Generated by Django 2.1.7 on 2019-03-05 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizational_area', '0006_auto_20190305_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalStructureAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructure')),
            ],
            options={
                'verbose_name': 'Organizational Structure Administrator',
                'verbose_name_plural': 'Organizational Structure Administrators',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AlterField(
            model_name='organizationalstructureofficeemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationalstructureofficeemployee',
            unique_together={('employee', 'office')},
        ),
    ]
