# Generated by Django 2.1.7 on 2019-03-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0011_auto_20190312_1034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationalstructureoffice',
            unique_together={('name', 'organizational_structure'), ('organizational_structure', 'is_default')},
        ),
    ]
