# Generated by Django 2.1.7 on 2019-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0014_remove_organizationalstructureoffice_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructureoffice',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
