# Generated by Django 2.1.7 on 2019-03-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0015_organizationalstructureoffice_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalstructure',
            name='seat',
        ),
    ]
