# Generated by Django 2.1.7 on 2019-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0016_remove_organizationalstructure_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(default='slug', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
