# Generated by Django 2.1.7 on 2019-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0019_auto_20190411_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructureoffice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
