# Generated by Django 3.0.3 on 2020-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0021_auto_20190503_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructureoffice',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
