# Generated by Django 3.0.5 on 2020-05-04 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizational_area', '0025_auto_20200406_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManageStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'organizational_structure')},
            },
        ),
    ]
