# Generated by Django 3.0.5 on 2020-05-05 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0027_auto_20200504_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Lo slug un carattere alfabetico', regex='^(?=.*[a-zA-Z])')]),
        ),
    ]
