# Generated by Django 4.2.5 on 2023-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizational_area",
            "0001_squashed_0032_organizationalstructureoffice_is_private",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organizationalstructureoffice",
            index=models.Index(
                fields=["is_active", "organizational_structure_id"],
                name="organizatio_is_acti_351a28_idx",
            ),
        ),
    ]
