# Generated by Django 5.1.8 on 2025-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizational_area",
            "0033_organizationalstructureoffice_organizatio_is_acti_351a28_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalstructure",
            name="app_io_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
