# Generated by Django 2.1.7 on 2019-02-24 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipments Type',
                'verbose_name': 'Equipment Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('unique_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=768, null=True)),
                ('seat', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structures',
                'verbose_name': 'Organizational Structure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure functions',
                'verbose_name': 'Organizational Structure function',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.EquipmentType')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.OrganizationalStructureFunction')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructure')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure locations',
                'verbose_name': 'Organizational Structure location',
                'ordering': ['organizational_structure'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructure')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure Offices',
                'verbose_name': 'Organizational Structure Office',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructureOffice')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure Office Employees',
                'verbose_name': 'Organizational Structure Office Employee',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.EquipmentType')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.OrganizationalStructureFunction')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructureOffice')),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure office locations',
                'verbose_name': 'Organizational Structure office location',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organizational Structure types',
                'verbose_name': 'Organizational Structure type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational_area.OrganizationalStructureType'),
        ),
    ]
