# Generated by Django 2.1.7 on 2019-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0002_auto_20190305_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
