# Generated by Django 2.1.7 on 2019-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0008_auto_20190305_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructureoffice',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='organizationalstructureoffice',
            unique_together={('name', 'organizational_structure')},
        ),
    ]
