# Generated by Django 2.1.7 on 2019-03-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0009_auto_20190305_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructureoffice',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='organizationalstructureoffice',
            unique_together={('organizational_structure', 'is_active'), ('name', 'organizational_structure')},
        ),
    ]
