# Generated by Django 2.1.7 on 2019-03-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0013_auto_20190312_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalstructureoffice',
            name='is_default',
        ),
    ]
