# Generated by Django 2.1.7 on 2019-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0017_organizationalstructure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructureoffice',
            name='slug',
            field=models.SlugField(default='sas', max_length=40),
        ),
    ]
