# Generated by Django 2.1.7 on 2019-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0020_auto_20190415_0945'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationalstructureoffice',
            unique_together={('slug', 'organizational_structure')},
        ),
    ]
