# Generated by Django 3.0.3 on 2020-03-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizational_area', '0023_organizationalstructure_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructureofficeemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
