# Generated by Django 3.0.7 on 2020-06-24 07:13

from django.db import migrations, models
import organizational_area.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0028_auto_20200505_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=organizational_area.models._logo_upload),
        ),
    ]
