# Generated by Django 3.0.7 on 2020-06-24 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0029_auto_20200624_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Lo slug deve contenere almeno un carattere alfabetico', regex='^(?=.*[a-zA-Z])')]),
        ),
    ]
