# Generated by Django 3.0.7 on 2020-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0030_auto_20200624_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructure',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructurefunction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructureofficeemployee',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructureofficelocation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationalstructuretype',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
