# Generated by Django 3.0.3 on 2020-03-03 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200303_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='read_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
