# Generated by Django 3.0.3 on 2020-03-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userchannel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
