# Generated by Django 3.1.6 on 2022-03-27 17:51

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20200623_0901'), ('accounts', '0003_auto_20210208_2216'), ('accounts', '0004_auto_20210409_2311'), ('accounts', '0005_auto_20220315_1219')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='attivo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('matricola_dipendente', models.CharField(blank=True, help_text='fonte CSA', max_length=10, null=True, verbose_name='Matricola Dipendente')),
                ('matricola_studente', models.CharField(blank=True, help_text='fonte Esse3', max_length=10, null=True, verbose_name='Matricola Studente')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Cognome')),
                ('taxpayer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='TaxPayer ID - codice fiscale')),
                ('email_notify', models.BooleanField(default=True, verbose_name='Notifiche mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
