# Generated by Django 3.2.12 on 2022-03-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0005_auto_20220315_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricola_dipendente',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricola_studente',
        ),
        migrations.AddField(
            model_name='user',
            name='identificativo_dipendente',
            field=models.CharField(blank=True, help_text='employee unique id', max_length=10, null=True, verbose_name='Identificativo Dipendente'),
        ),
        migrations.AddField(
            model_name='user',
            name='identificativo_utente',
            field=models.CharField(blank=True, help_text="eg: tax payer's identification number", max_length=10, null=True, verbose_name='Identificativo utente'),
        ),
    ]
