# Generated by Django 4.2.9 on 2024-10-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220328_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_user_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo aggiornamento manuale dei dati'),
        ),
    ]
