# Generated by Django 5.2.8 on 2025-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_user_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_context",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
