# Generated by Django 3.2 on 2021-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210208_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricola_dipendente',
            field=models.CharField(blank=True, help_text='fonte CSA', max_length=10, null=True, verbose_name='Matricola Dipendente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricola_studente',
            field=models.CharField(blank=True, help_text='fonte Esse3', max_length=10, null=True, verbose_name='Matricola Studente'),
        ),
    ]
