# titulus_ws settings
# you can ovverride them in settingslocal.py (if necessary)


import os


PROT_DOC_ENCODING="utf-8"

BASE_ROOT = os.path.dirname(os.path.abspath(__file__))

PROTOCOL_NAMESPACES = {
              'xsd': '{http://www.w3.org/2001/XMLSchema}',
              'ns0': '{http://www.kion.it/titulus}',
              'ns1': '{http://schemas.xmlsoap.org/soap/encoding/}',
              'ns2': '{URL}',
             }

PROTOCOL_NAMESPACES_DEBUG = {
              'xsd': '{http://www.w3.org/2001/XMLSchema}',
              'ns0': '{http://www.kion.it/titulus}',
              'ns1': '{http://schemas.xmlsoap.org/soap/encoding/}',
              'ns2': '{URL_PRE_PROD}',
             }

PROTOCOL_SEND_MAIL_DEBUG = True

FASCICOLAZIONE_SEPARATA = True

PATH_ROOT = 'titulus_ws'
PATH_XML_TEMPLATES = f'{BASE_ROOT}/xml_templates'

DOCUMENTO_ENTRATA_XML ="documento_entrata.xml"
FASCICOLO_XML ="fascicolo.xml"

DOCUMENTO_ENTRATA_PATH = f'{PATH_XML_TEMPLATES}/{DOCUMENTO_ENTRATA_XML}'
FASCICOLO_PATH = f'{PATH_XML_TEMPLATES}/{FASCICOLO_XML}'

TITOLARIO_DICT = (
    ("Amministrazione",
        (
            ("1/1","Normativa e relativa attuazione"),
            ("1/2","Statuto"),
            ("1/3","Regolamenti"),
            ("1/4","Stemma, gonfalone e sigillo"),
            ("1/5","Sistema informativo, sicurezza dell'informazione e sistema informatico"),
            ("1/6","Protezione dei dati personali"),
            ("1/7","Archivio"),
            ("1/8","Trasparenza e relazioni con il pubblico"),
            ("1/9","Strategie per il personale, organigramma e funzionigramma"),
            ("1/10","Rapporti sindacali e contrattazione"),
            ("1/11","Controllo di gestione e sistema qualità"),
            ("1/12","Statistica e auditing"),
            ("1/13","Elezioni e designazioni"),
            ("1/14","Associazioni e attività culturali, sportive e ricreative"),
            ("1/15","Editoria e attività informativo-promozionale"),
            ("1/16","Onorificenze, cerimoniale e attività di rappresentanza"),
            ("1/17","Politiche e interventi per le pari opportunità"),
            ("1/18","Interventi di carattere politico, economico, sociale e umanitario")
        )
    ),
    ("Organi di governo, gestione, controllo, consulenza e garanzia",
        (
            ("2/1","Rettore"),
            ("2/2","Prorettore vicario e delegati"),
            ("2/3","Direttore generale"),
            ("2/4","Direttore"),
            ("2/5","Presidente"),
            ("2/6","Senato accademico"),
            ("2/7","Consiglio di amministrazione"),
            ("2/8","Consiglio"),
            ("2/9","Giunta"),
            ("2/10","Commissione didattica paritetica docenti-studenti"),
            ("2/11","Nucleo di valutazione"),
            ("2/12","Collegio dei revisori dei conti"),
            ("2/13","Collegio di disciplina (per i docenti)"),
            ("2/14","Senato degli studenti"),
            ("2/15","Comitato unico di garanzia e per le pari opportunità"),
            ("2/16","Comitato tecnico scientifico"),
            ("2/17","Conferenza dei rettori delle università italiane - CRUI"),
            ("2/18","Comitato regionale di coordinamento"),
            ("2/19","Comitato per lo sport universitario")
        )
    ),
    ("Didattica, ricerca, programmazione e sviluppo",
        (
            ("3/1","Ordinamento didattico"),
            ("3/2","Corsi di studio"),
            ("3/3","Corsi a ordinamento speciale"),
            ("3/4","Corsi di specializzazione"),
            ("3/5","Master"),
            ("3/6","Corsi di dottorato"),
            ("3/7","Corsi di perfezionamento e corsi di formazione permanente"),
            ("3/8","Programmazione didattica, orario delle lezioni, gestione delle aule e degli spazi"),
            ("3/9","Gestione di esami di profitto, di laurea e di prove di idoneità"),
            ("3/10","Programmazione e sviluppo, comprese aree, macroaree e settori scientifico-disciplinari"),
            ("3/11","Strategie e valutazione della didattica e della ricerca"),
            ("3/12","Premi e borse di studio finalizzati e vincolati"),
            ("3/13","Progetti e finanziamenti"),
            ("3/14","Accordi per la didattica e la ricerca"),
            ("3/15","Rapporti con enti e istituti di area socio-sanitaria"),
            ("3/16","Opere dell'ingegno, brevetti e imprenditoria della ricerca"),
            ("3/17","Piani di sviluppo dell'università"),
            ("3/18","Cooperazione con paesi in via di sviluppo"),
            ("3/19","Attività per conto terzi")
        )
    ),
    ("Attività giuridico-legale",
        (
            ("4/1","Contenzioso"),
            ("4/2","Atti di liberalità"),
            ("4/3","Violazioni amministrative e reati"),
            ("4/4","Responsabilità civile, penale e amministrativa del personale"),
            ("4/5","Pareri e consulenze")
        )
    ),
    ("Studenti e laureati",
        (
            ("5/1","Orientamento, informazione e tutorato"),
            ("5/2","Selezioni, immatricolazioni e ammissioni"),
            ("5/3","Trasferimenti e passaggi"),
            ("5/4","Cursus studiorum e provvedimenti disciplinari"),
            ("5/5","Diritto allo studio, assicurazioni, benefici economici, tasse e contributi"),
            ("5/6","Tirocinio, formazione e attività di ricerca"),
            ("5/7","Servizi di assistenza socio-sanitaria e a richiesta"),
            ("5/8","Conclusione e cessazione della carriera di studio"),
            ("5/9","Esami di stato e ordini professionali"),
            ("5/10","Associazionismo, goliardia e manifestazioni organizzate da studenti o ex studenti"),
            ("5/11","Benefici Legge 390/91"),
            ("5/12","Servizi abitativi e mensa per gli studenti"),
            ("5/13","Attività culturali e ricreative")
        )
    ),
    ("Strutture didattiche, di ricerca e di servizio",
        (
            ("6/1","Poli"),
            ("6/2","Scuole e strutture di raccordo"),
            ("6/3","Dipartimenti"),
            ("6/4","Strutture a ordinamento speciale"),
            ("6/5","Scuole di specializzazione"),
            ("6/6","Scuole di dottorato"),
            ("6/7","Scuole interdipartimentali"),
            ("6/8","Centri"),
            ("6/9","Sistema bibliotecario"),
            ("6/10","Musei, pinacoteche e collezioni"),
            ("6/11","Consorzi ed enti a partecipazione universitaria"),
            ("6/12","Fondazioni"),
            ("6/13","Servizi di ristorazione, alloggi e foresterie")
        )
    ),
    ("Personale",
        (
            ("7/1","Concorsi e selezioni"),
            ("7/2","Assunzioni e cessazioni"),
            ("7/3","Comandi e distacchi"),
            ("7/4","Mansioni e incarichi"),
            ("7/5","Carriera e inquadramenti"),
            ("7/6","Retribuzione e compensi"),
            ("7/7","Adempimenti fiscali, contributivi e assicurativi"),
            ("7/8","Pre-ruolo, trattamento di quiescenza, buonuscita"),
            ("7/9","Dichiarazioni di infermità ed equo indennizzo"),
            ("7/10","Servizi a domanda individuale"),
            ("7/11","Assenze"),
            ("7/12","Tutela della salute e sorveglianza sanitaria"),
            ("7/13","Valutazione, giudizi di merito e provvedimenti disciplinari"),
            ("7/14","Formazione e aggiornamento professionale"),
            ("7/15","Deontologia professionale ed etica del lavoro"),
            ("7/16","Personale non strutturato")
        )
    ),
    ("Finanza, contabilità e bilancio",
        (
            ("8/1","Ricavi ed entrate"),
            ("8/2","Costi e uscite"),
            ("8/3","Bilancio"),
            ("8/4","Tesoreria, cassa e istituti di credito"),
            ("8/5","Imposte, tasse, ritenute previdenziali e assistenziali")
        )
    ),
    ("Edilizia e territorio",
        (
            ("9/1","Progettazione e costruzione di opere edilizie con relativi impianti"),
            ("9/2","Manutenzione ordinaria, straordinaria, ristrutturazione, restauro e destinazione d'uso"),
            ("9/3","Sicurezza e messa a norma degli ambienti di lavoro"),
            ("9/4","Telefonia e infrastruttura informatica"),
            ("9/5","Programmazione Territoriale")
        )
    ),
    ("Patrimonio, economato e provveditorato",
        (
            ("10/1","Acquisizione e gestione di beni immobili e relativi servizi"),
            ("10/2","Locazione di beni immobili, di beni mobili e relativi servizi"),
            ("10/3","Alienazione di beni immobili e di beni mobili"),
            ("10/4","Acquisizione e fornitura di beni mobili, di materiali e attrezzature non tecniche e di servizi"),
            ("10/5","Manutenzione di beni mobili"),
            ("10/6","Materiali, attrezzature, impiantistica e adempimenti tecnico-normativi"),
            ("10/7","Partecipazioni e investimenti finanziari"),
            ("10/8","Inventario, rendiconto patrimoniale, beni in comodato"),
            ("10/9","Patrimonio culturale – Tutela e valorizzazione"),
            ("10/10","Gestione dei rifiuti"),
            ("10/11","Albo dei fornitori")
        )
    ),
    # ("Oggetti diversi")
)

UO_DICT = (
            ("2015.1","AMMINISTRAZIONE CTC"),
            ("2013.1","AMMINISTRAZIONE DEMACS"),
            ("2025.1","AMMINISTRAZIONE DESF"),
            ("2020.1","AMMINISTRAZIONE DIAM"),
            ("2014.1","AMMINISTRAZIONE DIBEST"),
            ("2022.1","AMMINISTRAZIONE DICES"),
            ("2019.1","AMMINISTRAZIONE DIMEG"),
            ("2017.1","AMMINISTRAZIONE DIMES"),
            ("2018.1","AMMINISTRAZIONE DINCI"),
            ("2024.1","AMMINISTRAZIONE DISCAG"),
            ("2023.1","AMMINISTRAZIONE DISU"),
            ("2021.1","AMMINISTRAZIONE FARMACIA"),
            ("2016.1","AMMINISTRAZIONE FISICA"),
            ("2026.1","AMMINISTRAZIONE SPES"),
            ("2079.2","AREA AFFARI GENERALI"),
            ("0012.1","AREA BILANCIO E CICLO ATTIVO"),
            ("0019.3","AREA DIRITTO ALLO STUDIO"),
            ("2080.4","AREA EDILIZIA, VIABILITA' ED ESPROPRI"),
            ("0012.2","AREA FISCALE E CICLO PASSIVO"),
            ("2079.3","AREA GARE D'APPALTO"),
            ("2080.3","AREA IMPIANTI"),
            ("2032.1","AREA INFRASTRUTTURE INFORMATICHE E DI TELECOMUNICAZIONE"),
            ("917.3","AREA INTERNALIZZAZIONE"),
            ("917.1","AREA OFFERTA FORMATIVA"),
            ("917.4","AREA ORIENTAMENTO, INCLUSIONE E CAREER SERVICE"),
            ("896.4","AREA PERSONALE CONTRATTUALIZZATO E COLLABORATORI ESTERNI"),
            ("2066","AREA POST-LAUREA"),
            ("896.3","AREA PROFESSORI E RICERCATORI"),
            ("896.5","AREA RELAZIONI SINDACALI E SVILUPPO ORGANIZZATIVO"),
            ("0019.4","AREA RESIDENZIALITA'"),
            ("907","AREA RICERCA INNOVAZIONE E IMPATTO SOCIALE"),
            ("2032.3","AREA SERVIZI DI SUPPORTO E HELPDESK"),
            ("917.2","AREA SERVIZI DIDATTICI"),
            ("2079.4","AREA SERVIZI GENERALI"),
            ("2032.2","AREA SISTEMI INFORMATIVI"),
            ("0019.5","AREA SOCIALITA' E SALE CONVEGNI"),
            ("1.5","AVVOCATURA D'ATENEO"),
            ("640","CENTRO ARTI MUSICA E SPETTACOLO"),
            ("1790","CENTRO EDITORIALE E LIBRARIO"),
            ("1600","CENTRO LINGUISTICO DI ATENEO"),
            ("1860","CENTRO SANITARIO"),
            ("SI000017","COMITATO ETICO DI ATENEO"),
            ("SI000018","COMITATO UNICO DI GARANZIA"),
            ("2015.2","DIDATTICA CTC"),
            ("2013.2","DIDATTICA DEMACS"),
            ("2025.2","DIDATTICA DESF"),
            ("2020.2","DIDATTICA DIAM"),
            ("2014.2","DIDATTICA DIBEST"),
            ("2022.2","DIDATTICA DICES"),
            ("2019.2","DIDATTICA DIMEG"),
            ("2017.2","DIDATTICA DIMES"),
            ("2018.2","DIDATTICA DINCI"),
            ("2024.2","DIDATTICA DISCAG"),
            ("2023.2","DIDATTICA DISU"),
            ("2021.2","DIDATTICA FARMACIA"),
            ("2016.2","DIDATTICA FISICA"),
            ("2026.2","DIDATTICA SPES"),
            ("2014","DIPARTIMENTO DI BIOLOGIA, ECOLOGIA E SCIENZE DELLA TERRA"),
            ("2015","DIPARTIMENTO DI CHIMICA E TECNOLOGIE CHIMICHE"),
            ("2022","DIPARTIMENTO DI CULTURE EDUCAZIONE SOCIETA'"),
            ("2025","DIPARTIMENTO DI ECONOMIA STATISTICA E FINANZA"),
            ("2021","DIPARTIMENTO DI FARMACIA"),
            ("2016","DIPARTIMENTO DI FISICA"),
            ("2018","DIPARTIMENTO DI INGEGNERIA CIVILE"),
            ("2020","DIPARTIMENTO DI INGEGNERIA DELL'AMBIENTE"),
            ("2017","DIPARTIMENTO DI INGEGNERIA INFORMATICA MODELLISTICA ELETTRONICA E SISTEMISTICA"),
            ("2019","DIPARTIMENTO DI INGEGNERIA MECCANICA ENERGETICA E GESTIONALE"),
            ("2013","DIPARTIMENTO DI MATEMATICA E INFORMATICA"),
            ("2024","DIPARTIMENTO DI SCIENZE AZIENDALI GIURIDICHE"),
            ("2023","DIPARTIMENTO DI STUDI UMANISTICI"),
            ("2026","DIPARTIMENTO SCIENZE POLITICHE SOCIALI"),
            ("2079","DIREZIONE AFFARI GENERALI E ATTIVITA' NEGOZIALE"),
            ("19","DIREZIONE CENTRO RESIDENZIALE"),
            ("12","DIREZIONE FINANZIARIA"),
            ("1","DIREZIONE GENERALE"),
            ("896","DIREZIONE RISORSE UMANE"),
            ("2080","DIREZIONE TECNICA E PATRIMONIO IMMOBILIARE"),
            ("SI000006","LABORATORIO ALBANOLOGIA"),
            ("SI000005","LABORATORIO FONETICA"),
            ("SI000004","LABORATORIO LABDOC"),
            ("917","MACRO AREA DIDATTICA E SERVIZI AGLI STUDENTI"),
            ("2032","MACRO AREA SERVIZI INFORMATICI E TECNOLOGICI"),
            ("1750","MUSEO DI STORIA NATURALE ED ORTO BOTANICO"),
            ("SI000022","POLO DI INFANZIA"),
            ("1740","POLO ECONOMICO GIURIDICO"),
            ("1760","POLO SCIENTIFICO"),
            ("1820","POLO UMANISTICO"),
            ("2015.3","RICERCA CTC"),
            ("2013.3","RICERCA DEMACS"),
            ("2025.3","RICERCA DESF"),
            ("2020.3","RICERCA DIAM"),
            ("2014.3","RICERCA DIBEST"),
            ("2022.3","RICERCA DICES"),
            ("2019.3","RICERCA DIMEG"),
            ("2017.3","RICERCA DIMES"),
            ("2018.3","RICERCA DINCI"),
            ("2024.3","RICERCA DISCAG"),
            ("2023.3","RICERCA DISU"),
            ("2021.3","RICERCA FARMACIA"),
            ("2016.3","RICERCA FISICA"),
            ("2026.3","RICERCA SPES"),
            ("2012","RIMUSEUM - MUSEO PER L'AMBIENTE"),
            ("SI000020","RPCT"),
            ("2026.4","SCUOLA SUPERIORE DI SCIENZE DELLE AMM.NI PUBBLICHE"),
            ("1.3","SEGRETERIA DEL RETTORE"),
            ("1.4","SEGRETERIA ORGANI DI GOVERNO"),
            ("SI000014","Segreteria Studenti DIMEG"),
            ("SI000015","SERVIZI DIMEG"),
            ("1840.3","SERVIZIO AMMINISTRATIVO"),
            ("0019.2","SERVIZIO AMMINISTRATIVO CR"),
            ("2079.1","SERVIZIO ANTICORRUZIONE E LEGALITA'"),
            ("1840.1","SERVIZIO AUTOMAZIONE BIBLIOTECHE"),
            ("1.2","SERVIZIO COMUNICAZIONE"),
            ("1.6","SERVIZIO DI PREVENZIONE E PROTEZIONE"),
            ("2080.2","SERVIZIO ENERGY MANAGEMENT"),
            ("1840.2","SERVIZIO LOGISTICO"),
            ("1.7","SERVIZIO MONITORAGGIO, QUALITA' E VALUTAZIONE"),
            ("1.1","SERVIZIO PROGETTI INFRASTRUTTURE"),
            ("896.2","SERVIZIO PROGRAMMAZIONE E MONITORAGGIO"),
            ("2080.1","SERVIZIO QUALITA' E FACILITY MANAGEMENT"),
            ("SI000002","Servizio Ricezione Pec"),
            ("0019.1","SERVIZIO SISTEMI INFORMATIVI"),
            ("896.1","SERVIZIO TRATTAMENTO PREVIDENZIALE"),
            ("0012.1A","SETTORE BILANCIO"),
            ("0012.1B","SETTORE CICLO ATTIVO"),
            ("0012.2B","SETTORE CICLO PASSICO"),
            ("2066.1","SETTORE DOTTORATI DI RICERCA"),
            ("0012.2A","SETTORE EMOLUMENTI E FISCALE"),
            ("2066.3","SETTORE FORMAZIONE INSEGNANTI ED ESAMI DI STATO"),
            ("2079.2A","SETTORE GESTIONE DOCUMENTALE E PRIVACY"),
            ("0019.4A","SETTORE GESTIONE RESIDENZE"),
            ("907.2","SETTORE INNOVAZIONE E IMPATTO SOCIALE"),
            ("2066.2","SETTORE MASTER E CORSI POST LAUREA"),
            ("1.7B","SETTORE MONITORAGGIO PERFORMANCE"),
            ("2032.1A","SETTORE RETI E SICUREZZA"),
            ("907.1","SETTORE RICERCA"),
            ("1740.1","SETTORE RISORSE BIBLIOGRAFICHE"),
            ("1760.1","SETTORE RISORSE BIBLIOGRAFICHE"),
            ("1820.1","SETTORE RISORSE BIBLIOGRAFICHE"),
            ("1740.2","SETTORE SERVIZI AL PUBBLICO"),
            ("1760.2","SETTORE SERVIZI AL PUBBLICO"),
            ("1820.2","SETTORE SERVIZI AL PUBBLICO"),
            ("2032.2B","SETTORE SI AMMINISTRATIVI E DOCUMENTALI"),
            ("2032.2A","SETTORE SI PER RICERCA E DIDATTICA"),
            ("2032.1B","SETTORE SISTEMI E CLOUD"),
            ("1.7C","SETTORE STATISTICHE E REPORTING"),
            ("0019.4B","SETTORE TECNICO"),
            ("2032.1C","SETTORE TELEFONIA"),
            ("1.7A","SETTORE VALUTAZIONE E QUALITA'"),
            ("1840","SISTEMA BIBLIOTECARIO DI ATENEO"),
            ("SI000012","TECNICA DIMES"),
            ("SI000003","TECNICA ELABORAZIONE DATI DICES"),
            ("0","UNIVERSITA' DELLA CALABRIA")
)
