# Generated by Django 5.1.8 on 2025-04-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uni_ticket", "0029_task_is_printable_ticketcategorytask_is_printable"),
    ]

    operations = [
        migrations.CreateModel(
            name="IOService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "service_id",
                    models.CharField(max_length=50, verbose_name="ID del servizio"),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=50, verbose_name="API key del servizio"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Servizi App IO",
                "ordering": ["name", "service_id"],
            },
        ),
        migrations.CreateModel(
            name="IOLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.JSONField()),
                (
                    "log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_io_message",
                        to="uni_ticket.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IOServiceTicketCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="attivo"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_ticket.ticketcategory",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_io.ioservice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "category"),
                        name="unique_io_service_ticket_category",
                    )
                ],
            },
        ),
    ]
