# Generated by Django 5.2.8 on 2026-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_io", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iolog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ioservice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ioserviceticketcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
