# Generated by Django 3.2.12 on 2022-05-28 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0002_auto_20220327_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='protocol_date',
            field=models.DateTimeField(blank=True, help_text='Quando la richiesta è stata protocollata', null=True),
        ),
    ]
