# Generated by Django 3.2.15 on 2023-02-03 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0005_compiledticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiledticket',
            name='url_path',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
