# Generated by Django 3.2.17 on 2023-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0007_compiledticket_one_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Accessibile solo tramite URL'),
        ),
    ]
