# Generated by Django 3.2.17 on 2023-06-16 12:56

from django.conf import settings
import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('uni_ticket', '0008_ticketcategory_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="momento dell'azione")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="id dell'oggetto")),
                ('object_repr', models.CharField(max_length=200, verbose_name="rappr. dell'oggetto")),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Aggiunta '), (2, 'Modifica'), (3, 'Eliminazione')], verbose_name='flag di azione')),
                ('change_message', models.TextField(blank=True, verbose_name='messaggio di modifica')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'index_together': {('content_type', 'object_id')},
            },
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
