# Generated by Django 3.2.19 on 2023-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0010_populate_customlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-action_time'], 'verbose_name': 'voce di log', 'verbose_name_plural': 'voci di log'},
        ),
    ]
