# Generated by Django 4.2.5 on 2023-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni_ticket", "0011_alter_log_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="uni_ticket__content_dbfb39_idx",
            ),
        ),
    ]
