# Generated by Django 4.2.5 on 2023-10-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "uni_ticket",
            "0012_rename_log_content_type_object_id_uni_ticket__content_dbfb39_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticketassignment",
            index=models.Index(
                fields=["office_id", "follow"], name="uni_ticket__office__f42ab9_idx"
            ),
        ),
    ]
