# Generated by Django 4.2.5 on 2023-10-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni_ticket", "0013_ticketassignment_uni_ticket__office__f42ab9_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["code"], name="uni_ticket__code_3920e0_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["is_closed"], name="uni_ticket__is_clos_8d6d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_date"], name="uni_ticket__assigne_b1e790_idx"
            ),
        ),
    ]
