# Generated by Django 4.2.7 on 2023-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni_ticket", "0014_ticket_uni_ticket__code_3920e0_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="uni_ticket__code_3920e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="uni_ticket__is_clos_8d6d43_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="uni_ticket__assigne_b1e790_idx",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_closed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
