# Generated by Django 4.2.9 on 2024-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uni_ticket', '0015_remove_ticket_uni_ticket__code_3920e0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='uni_ticket__content_dbfb39_idx',
        ),
        migrations.AlterField(
            model_name='log',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')], verbose_name='flag di azione'),
        ),
        migrations.AlterField(
            model_name='ticketcategorywsprotocollo',
            name='protocollo_uo',
            field=models.CharField(choices=[('', '-')], max_length=12, verbose_name='UO'),
        ),
        # migrations.AlterIndexTogether(
            # name='log',
            # index_together={('content_type', 'object_id')},
        # ),
    ]
