# Generated by Django 4.2.9 on 2024-04-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0016_remove_log_uni_ticket__content_dbfb39_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='max_requests_per_user',
            field=models.IntegerField(default=0, help_text='0 = illimitate', verbose_name='Numero massimo di richieste per utente'),
        ),
    ]
