# Generated by Django 4.2.9 on 2024-04-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0017_ticketcategory_max_requests_per_user'),
    ]

    operations = [
        # migrations.RenameIndex(
            # model_name='log',
            # new_name='uni_ticket__content_dbfb39_idx',
            # old_fields=('content_type', 'object_id'),
        # ),
    ]
