# Generated by Django 4.2.16 on 2024-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0021_alter_task_options_alter_ticketcategorytask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
