# Generated by Django 4.2.16 on 2024-11-14 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0022_alter_ticket_is_closed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketassignment',
            name='uni_ticket__office__f42ab9_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
