# Generated by Django 4.2.16 on 2024-11-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0023_remove_ticketassignment_uni_ticket__office__f42ab9_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_closed'], name='uni_ticket__is_clos_8d6d44_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='uni_ticket__priorit_88a7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created'], name='uni_ticket__created_bb296d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'created'], name='uni_ticket__priorit_0666dd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['office', 'follow'], name='uni_ticket__office__f42ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['taken_date'], name='uni_ticket__taken_d_7d4fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['taken_by'], name='uni_ticket__taken_b_8d7e69_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['ticket', 'office'], name='uni_ticket__ticket__c50811_idx'),
        ),
    ]
