# Generated by Django 4.2.16 on 2024-11-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0025_remove_ticketassignment_uni_ticket__taken_b_8d7e69_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='uni_ticket__is_clos_8d6d43_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='uni_ticket__priorit_88a7f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='uni_ticket__priorit_0066dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketassignment',
            name='uni_ticket__ticket__c50811_idx',
        ),
    ]
