# Generated by Django 4.2.16 on 2024-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0026_remove_ticket_uni_ticket__is_clos_8d6d43_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_closed'], name='uni_ticket__is_clos_8d6d43_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='uni_ticket__priorit_88a7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'created'], name='uni_ticket__priorit_0066dd_idx'),
        ),
    ]
