# Generated by Django 5.1.7 on 2025-03-26 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uni_ticket', '0027_ticket_uni_ticket__is_clos_8d6d43_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-action_time'], 'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'},
        ),
        migrations.AlterField(
            model_name='log',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')], verbose_name='action flag'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time'),
        ),
        migrations.AlterField(
            model_name='log',
            name='change_message',
            field=models.TextField(blank=True, verbose_name='change message'),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_repr',
            field=models.CharField(max_length=200, verbose_name='object repr'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        # ~ migrations.AddIndex(
            # ~ model_name='log',
            # ~ index=models.Index(fields=['content_type', 'object_id'], name='uni_ticket__content_dbfb39_idx'),
        # ~ ),
    ]
