# Generated by Django 5.1.7 on 2025-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0028_alter_log_options_alter_log_action_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_printable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcategorytask',
            name='is_printable',
            field=models.BooleanField(default=False),
        ),
    ]
