# Generated by Django 5.1.8 on 2025-05-06 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0034_organizationalstructure_app_io_enabled"),
        ("uni_ticket", "0029_task_is_printable_ticketcategorytask_is_printable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOperatorNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[
                            (0, "Solo uffici della struttura attuale"),
                            (1, "Tutti gli uffici delle strutture coinvolte"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizational_area.organizationalstructure",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_ticket.ticket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
