# Generated by Django 5.1.8 on 2025-05-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0030_ticketoperatornote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketoperatornote",
            options={"ordering": ("created",)},
        ),
    ]
