# Generated by Django 5.2.8 on 2025-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0032_organizationalstructurealloweduserslist_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationalstructurealloweduserslist",
            options={
                "ordering": ["name", "created"],
                "verbose_name": "Lista di utenti abilitati",
            },
        ),
    ]
