# Generated by Django 5.2.8 on 2025-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0033_alter_organizationalstructurealloweduserslist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="allow_spid_cie",
            field=models.BooleanField(
                default=False,
                verbose_name="Accessibile solo con autenticazione SPID o CIE",
            ),
        ),
    ]
