# Generated by Django 5.2.8 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0035_alter_compiledticket_id_alter_log_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
