# Generated by Django 5.2.8 on 2026-04-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0035_alter_compiledticket_id_alter_log_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategoryinputlist",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TicketCategoryModuleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "Nascondi il campo"),
                            (2, "Mostra il campo"),
                            (3, "Modifica il valore"),
                        ]
                    ),
                ),
                ("value", models.TextField(blank=True, default="", max_length=20000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "category_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_ticket.ticketcategorymodule",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_rules",
                        to="uni_ticket.ticketcategoryinputlist",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_rules",
                        to="uni_ticket.ticketcategoryinputlist",
                    ),
                ),
            ],
        ),
    ]
