# Generated by Django 5.2.8 on 2026-10-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0036_ticket_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compiledticket",
            name="one_time",
        ),
    ]
