# Generated by Django 5.2.8 on 2026-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0036_ticketcategoryinputlist_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorymodulerule",
            name="condition",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
