# Generated by Django 2.2.4 on 2019-08-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0042_auto_20190806_0908"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketcategory",
            old_name="allow_operator",
            new_name="allow_employee",
        ),
    ]
