# Generated by Django 2.2.5 on 2019-09-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0050_ticketassignment_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketassignment",
            name="modified",
        ),
    ]
