# Generated by Django 3.0.3 on 2020-03-20 18:02

from django.db import migrations, models
import uni_ticket.models
import uni_ticket.validators


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0067_auto_20200320_0814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=uni_ticket.models._attachment_upload,
                validators=[
                    uni_ticket.validators.validate_file_extension,
                    uni_ticket.validators.validate_file_size,
                    uni_ticket.validators.validate_file_length,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategorycondition",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=uni_ticket.models._attachment_upload,
                validators=[
                    uni_ticket.validators.validate_file_extension,
                    uni_ticket.validators.validate_file_size,
                    uni_ticket.validators.validate_file_length,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategoryinputlist",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("CustomFileField", "Allegato (generico)"),
                    ("CustomImageField", "Allegato Immagine"),
                    ("CustomSignedP7MField", "Allegato P7M firmato"),
                    ("CustomPDFField", "Allegato PDF"),
                    ("CustomSignedPdfField", "Allegato PDF firmato"),
                    ("CustomDataField", "Allegato file dati (JSON, CSV, Excel)"),
                    ("CustomHiddenField", "Campo nascosto"),
                    ("CheckBoxField", "Checkbox"),
                    ("BaseDateField", "Data"),
                    ("BaseDateTimeField", "Data e Ora"),
                    ("DateStartEndComplexField", "Data inizio e Data fine"),
                    ("CustomEmailField", "E-mail"),
                    ("CustomComplexTableField", "Inserimenti multipli"),
                    ("CustomRadioBoxField", "Lista di opzioni (checkbox)"),
                    ("CustomSelectBoxField", "Lista di opzioni (tendina)"),
                    ("PositiveFloatField", "Numero con virgola positivo"),
                    ("PositiveIntegerField", "Numero intero positivo"),
                    ("ProtocolloField", "Protocollo (tipo/numero/data)"),
                    ("CustomCharField", "Testo"),
                    ("TextAreaField", "Testo lungo"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=uni_ticket.models._attachment_upload,
                validators=[
                    uni_ticket.validators.validate_file_extension,
                    uni_ticket.validators.validate_file_size,
                    uni_ticket.validators.validate_file_length,
                ],
            ),
        ),
    ]
