# Generated by Django 3.0.3 on 2020-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0079_auto_20200331_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorycondition",
            name="is_collapsable",
            field=models.BooleanField(
                default=True, verbose_name="Collassabile"),
        ),
    ]
