# Generated by Django 3.0.3 on 2020-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0087_auto_20200406_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategoryinputlist",
            name="valore",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Viene considerato solo se si sceglie 'Menu a tendina' oppure 'Serie di Opzioni'. (Es: valore1;valore2;valore3...)",
                max_length=500,
                verbose_name="Lista di Valori",
            ),
        ),
    ]
