# Generated by Django 3.0.5 on 2020-05-04 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0025_auto_20200406_1150"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uni_ticket", "0098_auto_20200429_1213"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStructureManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizational_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizational_area.OrganizationalStructure",
                    ),
                ),
            ],
            options={
                "ordering": ["employee"],
                "unique_together": {("employee", "organizational_structure")},
            },
        ),
    ]
