# Generated by Django 3.0.6 on 2020-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0108_ticketcategorywsarchipro_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorywsarchipro",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
