# Generated by Django 3.2.7 on 2021-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0175_alter_ticketcategorywsprotocollo_protocollo_uo_rpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorywsprotocollo",
            name="protocollo_uo_rpa_matricola",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Matricola RPA sul sistema di protocollo",
                max_length=255,
                verbose_name="RPA matricola",
            ),
        ),
    ]
