# Generated by Django 3.2.12 on 2022-04-13 21:08

import api_rest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationtoken',
            name='value',
            field=models.CharField(default=api_rest.models.create_token, help_text='Value of the Token', max_length=128, unique=True),
        ),
    ]
