# Generated by Django 5.2.8 on 2026-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0002_authorizationtoken_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizationtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
