# Generated by Django 2.1.7 on 2019-04-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketreply",
            name="attachment",
        ),
    ]
