# Generated by Django 2.1.7 on 2019-04-08 07:08

from django.db import migrations, models
import uni_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0003_ticketreply_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='status',
        ),
        # migrations.AlterField(
            # model_name='ticketreply',
            # name='attachment',
            # field=models.FileField(blank=True, null=True, upload_to=uni_ticket.models._attachment_upload),
        # ),
    ]
