# Generated by Django 2.1.7 on 2019-04-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0009_auto_20190415_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategorymodule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
