# Generated by Django 2.1.7 on 2019-04-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0012_auto_20190416_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategoryinputlist',
            name='category_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_ticket.TicketCategoryModule'),
        ),
    ]
