# Generated by Django 2.1.7 on 2019-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0016_auto_20190424_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_chiusura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_chiuso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='motivazione_chiusura',
            field=models.TextField(blank=True, null=True),
        ),
    ]
