# Generated by Django 2.1.7 on 2019-04-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0017_auto_20190424_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='structure',
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uni_ticket.Ticket'),
            preserve_default=False,
        ),
    ]
