# Generated by Django 2.1.7 on 2019-04-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0018_auto_20190424_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
