# Generated by Django 2.1.7 on 2019-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0021_auto_20190503_1546'),
        ('uni_ticket', '0022_auto_20190502_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority', '-created', 'code'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Ticket'},
        ),
        migrations.AlterUniqueTogether(
            name='ticketcategory',
            unique_together={('slug', 'organizational_structure')},
        ),
    ]
