# Generated by Django 2.2.1 on 2019-05-13 07:17

from django.db import migrations, models
import uni_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0025_ticketcategorycondition_is_printable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=uni_ticket.models._task_attachment_upload),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=uni_ticket.models._reply_attachment_upload),
        ),
    ]
