# Generated by Django 2.2.1 on 2019-05-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0026_auto_20190513_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
    ]
