# Generated by Django 2.2.1 on 2019-05-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0028_delete_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket2ticket',
            name='main_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate', to='uni_ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket2ticket',
            name='subordinate_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='uni_ticket.Ticket'),
        ),
    ]
