# Generated by Django 2.2.1 on 2019-05-21 10:29

from django.db import migrations, models
import uni_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0030_auto_20190520_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategoryinputlist',
            name='input_type',
            field=models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo')], max_length=33),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=uni_ticket.models._attachment_upload),
        ),
    ]
