# Generated by Django 2.2.1 on 2019-05-21 10:30

from django.db import migrations, models
import uni_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0031_auto_20190521_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=uni_ticket.models._reply_attachment_upload),
        ),
    ]
