# Generated by Django 2.2.2 on 2019-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0032_auto_20190521_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['is_preso_in_carico', 'is_chiuso', 'priority', '-created', 'code'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Ticket'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategoryinputlist',
            options={'verbose_name': 'Modulo di inserimento', 'verbose_name_plural': 'Moduli di inserimento'},
        ),
        migrations.RenameField(
            model_name='ticketcategoryinputlist',
            old_name='input_type',
            new_name='field_type',
        ),
    ]
