# Generated by Django 2.2.3 on 2019-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0033_auto_20190628_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategoryinputlist",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("CustomSignedP7MField", "Allegato P7M firmato"),
                    ("CustomFileField", "Allegato PDF"),
                    ("CustomSignedPdfField", "Allegato PDF firmato"),
                    ("CustomHiddenField", "Campo nascosto"),
                    ("CheckBoxField", "Checkbox"),
                    ("BaseDateField", "Data"),
                    ("BaseDateTimeField", "Data e Ora"),
                    ("DateStartEndComplexField", "Data inizio e Data fine"),
                    (
                        "DurataComeInteroField",
                        "Durata come numero intero (anni,mesi,ore)",
                    ),
                    ("CustomComplexTableField", "Inserimenti multipli"),
                    ("CustomRadioBoxField", "Lista di opzioni (checkbox)"),
                    ("CustomSelectBoxField", "Lista di opzioni (tendina)"),
                    ("PositiveFloatField", "Numero con virgola positivo"),
                    ("PositiveIntegerField", "Numero intero positivo"),
                    ("ProtocolloField", "Protocollo (tipo/numero/data)"),
                    ("CustomCharField", "Testo"),
                    ("TextAreaField", "Testo lungo"),
                ],
                max_length=100,
            ),
        ),
    ]
