# Generated by Django 2.2.3 on 2019-07-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0034_auto_20190704_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['is_chiuso', 'priority', 'is_preso_in_carico', '-created', 'code'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Ticket'},
        ),
    ]
