# Generated by Django 2.2.3 on 2019-07-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0037_auto_20190730_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketreply",
            name="from_owner",
        ),
    ]
