# Generated by Django 2.2.3 on 2019-07-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uni_ticket', '0038_remove_ticketreply_from_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='read',
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replies_read_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
