# Generated by Django 2.2.4 on 2019-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0045_auto_20190807_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket2ticket',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
