# Generated by Django 2.2.5 on 2019-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0048_auto_20190904_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
