# Generated by Django 2.2.5 on 2019-09-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0049_ticketassignment_readonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketassignment",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
