# Generated by Django 2.2.5 on 2019-09-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0051_remove_ticketassignment_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
