# Generated by Django 3.0.3 on 2020-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0055_auto_20200310_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
