# Generated by Django 3.0.3 on 2020-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0058_auto_20200317_1021"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="data_chiusura",
            new_name="closed_date",
        ),
    ]
