# Generated by Django 3.0.3 on 2020-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0064_auto_20200317_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='show_heading_text',
            field=models.BooleanField(default=True, verbose_name='Mostra agli utenti un testo di accettazione in fase di apertura nuovo ticket'),
        ),
    ]
