# Generated by Django 3.0.3 on 2020-03-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0066_auto_20200319_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='allow_employee',
            field=models.BooleanField(default=True, verbose_name='Accessibile a Dipendenti'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='allow_guest',
            field=models.BooleanField(default=True, verbose_name='Accessibile a Ospiti'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='allow_user',
            field=models.BooleanField(default=True, verbose_name='Accessibile a Studenti'),
        ),
    ]
