# Generated by Django 3.0.3 on 2020-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0072_ticketcategorytask"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorytask",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Visibile nei ticket"),
        ),
    ]
