# Generated by Django 3.0.3 on 2020-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0074_auto_20200327_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="confirm_message_text",
            field=models.CharField(
                blank=True,
                help_text="Es: 'Hai correttamente confermato la tua partecipazione'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="is_notify",
            field=models.BooleanField(
                default=False, verbose_name="Ticket di tipo Notifica"
            ),
        ),
    ]
