# Generated by Django 3.0.3 on 2020-03-31 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uni_ticket', '0078_auto_20200330_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategoryinputlist',
            name='pre_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taken_by_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='confirm_message_text',
            field=models.CharField(blank=True, help_text='Es: \'Hai correttamente confermato la tua partecipazione\'. Apri e chiudi le parentesi graffe per inserire il codice del ticket. Lascia vuoto per usare il testo predefinito "Ticket "{}" creato con successo"', max_length=255, null=True, verbose_name='Messaggio di conferma'),
        ),
    ]
