# Generated by Django 3.0.3 on 2020-04-02 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uni_ticket", "0081_auto_20200402_0109"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="closed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_closed_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
