# Generated by Django 3.0.3 on 2020-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0082_task_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='allow_anonymous',
            field=models.BooleanField(default=False, verbose_name='Accessibile a Utenti anonimi'),
        ),
    ]
