# Generated by Django 3.0.3 on 2020-04-06 09:48

from django.db import migrations, models
import uni_ticket.models
import uni_ticket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0084_auto_20200406_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=uni_ticket.models._attachment_upload, validators=[uni_ticket.validators.validate_file_extension, uni_ticket.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ticketcategorytask',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=uni_ticket.models._attachment_upload, validators=[uni_ticket.validators.validate_file_extension, uni_ticket.validators.validate_file_size]),
        ),
    ]
