# Generated by Django 3.0.3 on 2020-04-06 09:49

from django.db import migrations, models
import uni_ticket.models
import uni_ticket.validators


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0085_auto_20200406_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategorycondition",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=uni_ticket.models._attachment_upload,
                validators=[
                    uni_ticket.validators.validate_file_extension,
                    uni_ticket.validators.validate_file_size,
                    uni_ticket.validators.validate_file_length,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=uni_ticket.models._attachment_upload,
                validators=[
                    uni_ticket.validators.validate_file_extension,
                    uni_ticket.validators.validate_file_size,
                    uni_ticket.validators.validate_file_length,
                ],
            ),
        ),
    ]
