# Generated by Django 3.0.3 on 2020-04-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0091_ticketcategory_receive_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='receive_email',
            field=models.BooleanField(default=False, help_text='Operatori ricevono notifica email per ogni ticket aperto', verbose_name='Mail ad operatori'),
        ),
    ]
