# Generated by Django 3.0.3 on 2020-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0093_auto_20200424_0834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategory",
            name="receive_email",
            field=models.BooleanField(
                default=False,
                help_text="Invia email a operatori per ogni ticket aperto",
                verbose_name="Mail ad operatori",
            ),
        ),
    ]
