# Generated by Django 3.0.5 on 2020-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0100_auto_20200504_2302"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserStructureManager",
        ),
    ]
