# Generated by Django 3.0.6 on 2020-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0107_ticketcategorywsarchipro"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategorywsarchipro",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
