# Generated by Django 3.0.6 on 2020-05-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0028_auto_20200505_1149'),
        ('uni_ticket', '0111_auto_20200521_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructurewsarchipro',
            name='organizational_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.OrganizationalStructure'),
        ),
    ]
