# Generated by Django 3.0.6 on 2020-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0112_auto_20200521_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructurewsarchipro',
            name='protocollo_cod_titolario',
            field=models.CharField(default=3, max_length=12, verbose_name='Codice titolario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_cod_titolario',
            field=models.CharField(default=3, max_length=12, verbose_name='Codice titolario'),
            preserve_default=False,
        ),
    ]
