# Generated by Django 3.0.6 on 2020-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0115_auto_20200522_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalstructurewsarchipro",
            name="protocollo_aoo",
            field=models.CharField(default=1, max_length=12, verbose_name="AOO"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticketcategorywsarchipro",
            name="protocollo_aoo",
            field=models.CharField(default=1, max_length=12, verbose_name="AOO"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizationalstructurewsarchipro",
            name="protocollo_fascicolo_anno",
            field=models.IntegerField(verbose_name="Fascicolo anno"),
        ),
        migrations.AlterField(
            model_name="organizationalstructurewsarchipro",
            name="protocollo_template",
            field=models.TextField(
                help_text="Template XML che descrive il flusso",
                verbose_name="XML template",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategorywsarchipro",
            name="protocollo_fascicolo_anno",
            field=models.IntegerField(verbose_name="Fascicolo anno"),
        ),
        migrations.AlterField(
            model_name="ticketcategorywsarchipro",
            name="protocollo_template",
            field=models.TextField(
                help_text="Template XML che descrive il flusso",
                verbose_name="XML template",
            ),
        ),
    ]
