# Generated by Django 3.0.7 on 2020-06-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0122_ticketcategorydefaultreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategorydefaultreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
