# Generated by Django 3.0.7 on 2020-06-18 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uni_ticket', '0124_ticket_closing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='compiled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
