# Generated by Django 3.0.7 on 2020-06-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0137_auto_20200630_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_agd',
        ),
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_aoo',
        ),
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_email',
        ),
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_id_uo',
        ),
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_template',
        ),
        migrations.RemoveField(
            model_name='ticketcategorywsarchipro',
            name='protocollo_uo',
        ),
    ]
