# Generated by Django 3.0.7 on 2020-06-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0138_auto_20200630_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalstructurewsarchipro',
            name='protocollo_template',
        ),
    ]
