# Generated by Django 3.0.7 on 2020-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0139_remove_organizationalstructurewsarchipro_protocollo_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalstructurewsarchipro',
            options={'ordering': ['-created'], 'verbose_name': 'Configurazione WSArchiPro Struttura', 'verbose_name_plural': 'Configurazioni WSArchiPro Strutture'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategorywsarchipro',
            options={'ordering': ['-created'], 'verbose_name': 'Configurazione WSArchiPro Categoria', 'verbose_name_plural': 'Configurazioni WSArchiPro Categorie'},
        ),
        migrations.AddField(
            model_name='organizationalstructurewsarchipro',
            name='protocollo_password',
            field=models.CharField(default='username', max_length=255, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalstructurewsarchipro',
            name='protocollo_username',
            field=models.CharField(default='password', max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
