# Generated by Django 3.0.7 on 2020-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0140_auto_20200701_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationalstructurewsarchipro",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
