# Generated by Django 3.0.7 on 2020-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0143_auto_20200702_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalstructurewsarchipro',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Denominazione configurazione'),
        ),
    ]
