# Generated by Django 3.0.7 on 2020-07-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0145_auto_20200703_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcategory',
            old_name='is_notify',
            new_name='is_notification',
        ),
    ]
