# Generated by Django 3.0.7 on 2020-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0146_auto_20200716_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_notification',
            field=models.BooleanField(default=False, verbose_name='Richiesta di tipo Notifica'),
        ),
    ]
