# Generated by Django 3.1.2 on 2020-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0151_auto_20201020_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
