# Generated by Django 3.1.6 on 2021-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0158_organizationalstructurealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
