# Generated by Django 3.2.7 on 2021-09-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uni_ticket", "0160_ticketcategory_user_multiple_open_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCategoryWSProtocollo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "protocollo_cod_titolario",
                    models.CharField(
                        choices=[
                            (
                                "Amministrazione",
                                (
                                    ("1/1", "Normativa e relativa attuazione"),
                                    ("1/2", "Statuto"),
                                    ("1/3", "Regolamenti"),
                                    ("1/4", "Stemma, gonfalone e sigillo"),
                                    (
                                        "1/5",
                                        "Sistema informativo, sicurezza dell'informazione e sistema informatico",
                                    ),
                                    ("1/6", "Protezione dei dati personali"),
                                    ("1/7", "Archivio"),
                                    ("1/8", "Trasparenza e relazioni con il pubblico"),
                                    (
                                        "1/9",
                                        "Strategie per il personale, organigramma e funzionigramma",
                                    ),
                                    ("1/10", "Rapporti sindacali e contrattazione"),
                                    ("1/11", "Controllo di gestione e sistema qualità"),
                                    ("1/12", "Statistica e auditing"),
                                    ("1/13", "Elezioni e designazioni"),
                                    (
                                        "1/14",
                                        "Associazioni e attività culturali, sportive e ricreative",
                                    ),
                                    (
                                        "1/15",
                                        "Editoria e attività informativo-promozionale",
                                    ),
                                    (
                                        "1/16",
                                        "Onorificenze, cerimoniale e attività di rappresentanza",
                                    ),
                                    (
                                        "1/17",
                                        "Politiche e interventi per le pari opportunità",
                                    ),
                                    (
                                        "1/18",
                                        "Interventi di carattere politico, economico, sociale e umanitario",
                                    ),
                                ),
                            ),
                            (
                                "Organi di governo, gestione, controllo, consulenza e garanzia",
                                (
                                    ("2/1", "Rettore"),
                                    ("2/2", "Prorettore vicario e delegati"),
                                    ("2/3", "Direttore generale"),
                                    ("2/4", "Direttore"),
                                    ("2/5", "Presidente"),
                                    ("2/6", "Senato accademico"),
                                    ("2/7", "Consiglio di amministrazione"),
                                    ("2/8", "Consiglio"),
                                    ("2/9", "Giunta"),
                                    (
                                        "2/10",
                                        "Commissione didattica paritetica docenti-studenti",
                                    ),
                                    ("2/11", "Nucleo di valutazione"),
                                    ("2/12", "Collegio dei revisori dei conti"),
                                    ("2/13", "Collegio di disciplina (per i docenti)"),
                                    ("2/14", "Senato degli studenti"),
                                    (
                                        "2/15",
                                        "Comitato unico di garanzia e per le pari opportunità",
                                    ),
                                    ("2/16", "Comitato tecnico scientifico"),
                                    (
                                        "2/17",
                                        "Conferenza dei rettori delle università italiane - CRUI",
                                    ),
                                    ("2/18", "Comitato regionale di coordinamento"),
                                    ("2/19", "Comitato per lo sport universitario"),
                                ),
                            ),
                            (
                                "Didattica, ricerca, programmazione e sviluppo",
                                (
                                    ("3/1", "Ordinamento didattico"),
                                    ("3/2", "Corsi di studio"),
                                    ("3/3", "Corsi a ordinamento speciale"),
                                    ("3/4", "Corsi di specializzazione"),
                                    ("3/5", "Master"),
                                    ("3/6", "Corsi di dottorato"),
                                    (
                                        "3/7",
                                        "Corsi di perfezionamento e corsi di formazione permanente",
                                    ),
                                    (
                                        "3/8",
                                        "Programmazione didattica, orario delle lezioni, gestione delle aule e degli spazi",
                                    ),
                                    (
                                        "3/9",
                                        "Gestione di esami di profitto, di laurea e di prove di idoneità",
                                    ),
                                    (
                                        "3/10",
                                        "Programmazione e sviluppo, comprese aree, macroaree e settori scientifico-disciplinari",
                                    ),
                                    (
                                        "3/11",
                                        "Strategie e valutazione della didattica e della ricerca",
                                    ),
                                    (
                                        "3/12",
                                        "Premi e borse di studio finalizzati e vincolati",
                                    ),
                                    ("3/13", "Progetti e finanziamenti"),
                                    ("3/14", "Accordi per la didattica e la ricerca"),
                                    (
                                        "3/15",
                                        "Rapporti con enti e istituti di area socio-sanitaria",
                                    ),
                                    (
                                        "3/16",
                                        "Opere dell'ingegno, brevetti e imprenditoria della ricerca",
                                    ),
                                    ("3/17", "Piani di sviluppo dell'università"),
                                    (
                                        "3/18",
                                        "Cooperazione con paesi in via di sviluppo",
                                    ),
                                    ("3/19", "Attività per conto terzi"),
                                ),
                            ),
                            (
                                "Attività giuridico-legale",
                                (
                                    ("4/1", "Contenzioso"),
                                    ("4/2", "Atti di liberalità"),
                                    ("4/3", "Violazioni amministrative e reati"),
                                    (
                                        "4/4",
                                        "Responsabilità civile, penale e amministrativa del personale",
                                    ),
                                    ("4/5", "Pareri e consulenze"),
                                ),
                            ),
                            (
                                "Studenti e laureati",
                                (
                                    ("5/1", "Orientamento, informazione e tutorato"),
                                    ("5/2", "Selezioni, immatricolazioni e ammissioni"),
                                    ("5/3", "Trasferimenti e passaggi"),
                                    (
                                        "5/4",
                                        "Cursus studiorum e provvedimenti disciplinari",
                                    ),
                                    (
                                        "5/5",
                                        "Diritto allo studio, assicurazioni, benefici economici, tasse e contributi",
                                    ),
                                    (
                                        "5/6",
                                        "Tirocinio, formazione e attività di ricerca",
                                    ),
                                    (
                                        "5/7",
                                        "Servizi di assistenza socio-sanitaria e a richiesta",
                                    ),
                                    (
                                        "5/8",
                                        "Conclusione e cessazione della carriera di studio",
                                    ),
                                    ("5/9", "Esami di stato e ordini professionali"),
                                    (
                                        "5/10",
                                        "Associazionismo, goliardia e manifestazioni organizzate da studenti o ex studenti",
                                    ),
                                    ("5/11", "Benefici Legge 390/91"),
                                    (
                                        "5/12",
                                        "Servizi abitativi e mensa per gli studenti",
                                    ),
                                    ("5/13", "Attività culturali e ricreative"),
                                ),
                            ),
                            (
                                "Strutture didattiche, di ricerca e di servizio",
                                (
                                    ("6/1", "Poli"),
                                    ("6/2", "Scuole e strutture di raccordo"),
                                    ("6/3", "Dipartimenti"),
                                    ("6/4", "Strutture a ordinamento speciale"),
                                    ("6/5", "Scuole di specializzazione"),
                                    ("6/6", "Scuole di dottorato"),
                                    ("6/7", "Scuole interdipartimentali"),
                                    ("6/8", "Centri"),
                                    ("6/9", "Sistema bibliotecario"),
                                    ("6/10", "Musei, pinacoteche e collezioni"),
                                    (
                                        "6/11",
                                        "Consorzi ed enti a partecipazione universitaria",
                                    ),
                                    ("6/12", "Fondazioni"),
                                    (
                                        "6/13",
                                        "Servizi di ristorazione, alloggi e foresterie",
                                    ),
                                ),
                            ),
                            (
                                "Personale",
                                (
                                    ("7/1", "Concorsi e selezioni"),
                                    ("7/2", "Assunzioni e cessazioni"),
                                    ("7/3", "Comandi e distacchi"),
                                    ("7/4", "Mansioni e incarichi"),
                                    ("7/5", "Carriera e inquadramenti"),
                                    ("7/6", "Retribuzione e compensi"),
                                    (
                                        "7/7",
                                        "Adempimenti fiscali, contributivi e assicurativi",
                                    ),
                                    (
                                        "7/8",
                                        "Pre-ruolo, trattamento di quiescenza, buonuscita",
                                    ),
                                    (
                                        "7/9",
                                        "Dichiarazioni di infermità ed equo indennizzo",
                                    ),
                                    ("7/10", "Servizi a domanda individuale"),
                                    ("7/11", "Assenze"),
                                    (
                                        "7/12",
                                        "Tutela della salute e sorveglianza sanitaria",
                                    ),
                                    (
                                        "7/13",
                                        "Valutazione, giudizi di merito e provvedimenti disciplinari",
                                    ),
                                    (
                                        "7/14",
                                        "Formazione e aggiornamento professionale",
                                    ),
                                    (
                                        "7/15",
                                        "Deontologia professionale ed etica del lavoro",
                                    ),
                                    ("7/16", "Personale non strutturato"),
                                ),
                            ),
                            (
                                "Finanza, contabilità e bilancio",
                                (
                                    ("8/1", "Ricavi ed entrate"),
                                    ("8/2", "Costi e uscite"),
                                    ("8/3", "Bilancio"),
                                    ("8/4", "Tesoreria, cassa e istituti di credito"),
                                    (
                                        "8/5",
                                        "Imposte, tasse, ritenute previdenziali e assistenziali",
                                    ),
                                ),
                            ),
                            (
                                "Edilizia e territorio",
                                (
                                    (
                                        "9/1",
                                        "Progettazione e costruzione di opere edilizie con relativi impianti",
                                    ),
                                    (
                                        "9/2",
                                        "Manutenzione ordinaria, straordinaria, ristrutturazione, restauro e destinazione d'uso",
                                    ),
                                    (
                                        "9/3",
                                        "Sicurezza e messa a norma degli ambienti di lavoro",
                                    ),
                                    ("9/4", "Telefonia e infrastruttura informatica"),
                                    ("9/5", "Programmazione Territoriale"),
                                ),
                            ),
                            (
                                "Patrimonio, economato e provveditorato",
                                (
                                    (
                                        "10/1",
                                        "Acquisizione e gestione di beni immobili e relativi servizi",
                                    ),
                                    (
                                        "10/2",
                                        "Locazione di beni immobili, di beni mobili e relativi servizi",
                                    ),
                                    (
                                        "10/3",
                                        "Alienazione di beni immobili e di beni mobili",
                                    ),
                                    (
                                        "10/4",
                                        "Acquisizione e fornitura di beni mobili, di materiali e attrezzature non tecniche e di servizi",
                                    ),
                                    ("10/5", "Manutenzione di beni mobili"),
                                    (
                                        "10/6",
                                        "Materiali, attrezzature, impiantistica e adempimenti tecnico-normativi",
                                    ),
                                    (
                                        "10/7",
                                        "Partecipazioni e investimenti finanziari",
                                    ),
                                    (
                                        "10/8",
                                        "Inventario, rendiconto patrimoniale, beni in comodato",
                                    ),
                                    (
                                        "10/9",
                                        "Patrimonio culturale – Tutela e valorizzazione",
                                    ),
                                    ("10/10", "Gestione dei rifiuti"),
                                    ("10/11", "Albo dei fornitori"),
                                ),
                            ),
                        ],
                        max_length=12,
                        verbose_name="Codice titolario",
                    ),
                ),
                (
                    "protocollo_fascicolo_numero",
                    models.IntegerField(verbose_name="Fascicolo numero"),
                ),
                (
                    "protocollo_fascicolo_anno",
                    models.IntegerField(verbose_name="Fascicolo anno"),
                ),
                (
                    "ticket_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_ticket.ticketcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione WSArchiPro Categoria",
                "verbose_name_plural": "Configurazioni WSArchiPro Categorie",
                "ordering": ["-created"],
            },
        ),
        migrations.DeleteModel(
            name="TicketCategoryWSArchiPro",
        ),
    ]
