# Generated by Django 3.2.7 on 2021-09-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizational_area", "0032_organizationalstructureoffice_is_private"),
        ("uni_ticket", "0161_auto_20210924_1330"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalStructureWSProtocollo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Denominazione configurazione"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "protocollo_username",
                    models.CharField(max_length=255, verbose_name="Username"),
                ),
                (
                    "protocollo_password",
                    models.CharField(max_length=255, verbose_name="Password"),
                ),
                ("protocollo_aoo", models.CharField(
                    max_length=12, verbose_name="AOO")),
                (
                    "protocollo_agd",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="AGD"
                    ),
                ),
                (
                    "protocollo_uo",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="UO"
                    ),
                ),
                (
                    "protocollo_email",
                    models.EmailField(
                        blank=True,
                        help_text="Se vuoto: amministrazione@pec.unical.it",
                        max_length=255,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "organizational_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizational_area.organizationalstructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione WS Protocollo Struttura",
                "verbose_name_plural": "Configurazioni WS Protocollo Strutture",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcategorywsprotocollo",
            options={
                "ordering": ["-created"],
                "verbose_name": "Configurazione WS Protocollo Categoria",
                "verbose_name_plural": "Configurazioni WS Protocollo Categorie",
            },
        ),
        migrations.DeleteModel(
            name="OrganizationalStructureWSArchiPro",
        ),
    ]
