# Generated by Django 3.1.6 on 2022-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_ticket', '0176_ticketcategorywsprotocollo_protocollo_uo_rpa_matricola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategorywsprotocollo',
            name='protocollo_email',
            field=models.EmailField(blank=True, help_text='Se vuoto: default@example.pec.it', max_length=255, null=True, verbose_name='E-mail'),
        ),
    ]
